version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: dependency-updates
  labels:
  - "dependencies"
  ignore:
  # We cannot update this one until API26. Ignore range should slide with known versions so we stay informed.
  - dependency-name: org.apache.commons:commons-compress
    versions:
    - ">= 1.12, < 1.21"
  # We cannot use current versions of material-dialogs with Java. It went Kotlin-only.
  - dependency-name: com.afollestad.material-dialogs:core
    versions:
    - ">= 2.a, < 3"
  - dependency-name: com.afollestad.material-dialogs:core
    versions:
    - ">= 3.a, < 4"
