language: android
sudo: false
env:
  global:
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    # Android API-16 is required to use the emulator with API 16
    - android-16
    # Our current build target
    - android-26
    - extra-android-m2repository
    # Android Emulator API 16 benchmarks as fastest:
    #   https://medium.com/zendesk-engineering/speeding-up-android-builds-on-travis-ci-1bb4cdbd9c62
    - sys-img-armeabi-v7a-android-16

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

# Emulator Management: Create, Start and prep our tests while we Wait
before_script:
  - echo no | android create avd --force -n test -t android-16 --sdcard 10M --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - ./gradlew assembleDebug assembleDebugAndroidTest
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew test :AnkiDroid:connectedCheck

notifications:
  email:
    - flerda+ankidroid-continuous@gmail.com
