language: android

jdk:
  - oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=20  # 20 minutes, vs the 2 minute default
    - ADB_TRACE=all,sockets
    - ABI=x86_64
    - EMU_FLAVOR=default # use google_apis flavor if no default flavor emulator
    # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  matrix:
   #- API=15 # only runs locally. Create+Start once from AndroidStudio to init sdcard. Then only from command-line w/-engine classic
   #- API=16 ABI=armeabi-v7a AUDIO=-no-audio
   #- API=17 ABI=armeabi-v7a
   #- API=18 ABI=armeabi-v7a # API18 has started being flaky
   #- API=19 ABI=armeabi-v7a # Kernel/emulator mismatch, and emulator-29+ doesn't support "-engine classic" to fix
   # API 20 was Android Wear only
   #- API=21
   #- API=22
   #- API=23
   #- API=24
   #- API=25 
   #- API=26 ABI=x86_64 # Fails with unrecognized tests? orchestrator change or something?
   #- API=27
   - API=28
   - API=Q

# This block currently does not work, but it used to. API=28/Q are probably fixable
# but we don't need allow_failures to be on in master to work through them
#matrix:
#  fast_finish: true # We can report success without waiting for these
#  allow_failures:
#     - env: API=28
#     - env: API=Q

jobs:
  include:
    # The test stage is implicit, we only need to define a post-test stage for codacy finalization
    - stage: finalize_coverage
      env: FINALIZE_COVERAGE=TRUE API=NONE
      install: skip
      script: echo finalize codacy coverage uploads

android:
  components:
    # installing tools to start, then use `sdkmanager` below to get the rest
    - tools

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Emulator Management: Create, Start and Wait
install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid harmless sdkmanager warning
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null # A second time per Travis docs, gets latest versions
  - echo y | sdkmanager "build-tools;28.0.3" >/dev/null # Implicit gradle dependency - gradle drives changes
  - echo y | sdkmanager "platforms;android-$API" >/dev/null # We need the API of the emulator we will run
  - echo y | sdkmanager "platforms;android-28" >/dev/null # We need the API of the current compileSdkVersion from gradle.properties
  - echo y | sdkmanager --channel=4 "emulator" >/dev/null # Experiment with canary, specifying 28.0.3 (prior version) did not work
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | sdkmanager "system-images;android-$API;$EMU_FLAVOR;$ABI" #>/dev/null # install our emulator
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI" -c 10M
  - emulator -debug all -avd test -no-accel -no-snapshot-load -no-snapshot-save -screen no-touch -no-window $AUDIO -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &
  - travis_wait 20 ./tools/ci/android_wait_longer_for_emulator.sh
  - adb shell input keyevent 82 &
  - adb kill-server # Force an adb restart so our build.gradle gets a chance to set a timeout larger than 5s

script:
  - ./gradlew jacocoTestReport

# Codacy integration, partials for all APIs, then an optional finalize
after_success:
  - wget --progress=dot:giga -O ~/codacy-coverage-reporter-assembly-latest.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.2/codacy-coverage-reporter-4.0.2-assembly.jar
  - if [[ ( "$API" != "NONE" ) ]]; then java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r AnkiDroid/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml --partial; fi
  - if [[ ( "$FINALIZE_COVERAGE" == "TRUE" ) ]]; then java -jar ~/codacy-coverage-reporter-assembly-latest.jar final; fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    - flerda+ankidroid-continuous@gmail.com
