language: java
branches:
  only:
    - /^release-[0-9.]*$/
    - /^develop$/

before_install:
  # Needed to run Android SDK tools, which are 32-bit binaries.
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
before_script:
  # Configure Android SDK tools and platforms required to build.
  - ./tools/travis/continuous-setup.sh ..
script: "./tools/travis/continuous-build-and-test.sh"

notifications:
  email:
    - flerda+ankidroid-continuous@gmail.com
