[versions]
compileSdk = "34"
minSdk = "23"  # also in testlib/build.gradle.kts
targetSdk = "33"  # also in  ../robolectricDownloader.gradle
acra = '5.11.3'
amazonappstorepublisher = "0.1.0"
androidGradlePlugin = "8.4.1"
androidxActivity = "1.9.0"
androidxAnnotation = "1.8.0"
androidxAppCompat = "1.7.0"
androidxBrowser = "1.8.0"
androidxConstraintlayout = "2.1.4"
androidxCoreKtx = "1.13.1"
androidxExifinterface = "1.3.7"
androidxFragmentKtx = "1.7.1"
androidxImageCropper = "4.5.0"
androidxMedia = "1.7.0"
androidxPreferenceKtx = "1.2.1"
androidxRecyclerview = "1.3.2"
androidxRunner = "1.5.2"
androidxSqliteFramework = "2.4.0"
androidxSwiperefreshlayout = "1.1.0"
androidxTextCore = "1.5.0"
androidxUiautomator = "2.3.0"
androidxViewpager2 = "1.1.0"
androidxWebkit = "1.11.0"
annotations = "24.1.0"
ankiBackend = '0.1.38-anki24.04.1'
autoService = "1.1.1"
autoServiceAnnotations = "1.1.1"
colorpicker = "1.2.0"
commonsCollections4 = "4.4"
commonsCompress = "1.26.2"
commonsExec = "1.4.0"
commonsIo = "2.16.1"
coroutines = '1.8.1'
core = "3.3.0"
desugar-jdk-libs-nio = "2.0.4"
drawer = "1.0.3"
dokka = "1.9.20"
espresso = '3.5.1'
mikehardyGoogleAnalyticsJava7 = "2.0.13"
hamcrest = "2.2"
javaSemver = "0.10.2"
json = "20240303"
jsoup = "1.17.2"
androidTestJunit = "1.1.5"
junitJupiter = "5.10.2"
junitJupiterParams = "5.10.2"
junitVintageEngine = "5.10.2"
kotlin = '2.0.0'
kotlinReflect = "2.0.0"
kotlinTest = "2.0.0"
kotlinxSerializationJson = "1.6.3"
ktlint = "11.6.1"
leakcanaryAndroid = "2.14"
lint = '31.4.1'
material = "1.12.0"
materialTapTargetPrompt = "3.3.2"
mockitoInline = "5.2.0"
mockitoKotlin = "5.3.1"
mockk = "1.13.11"
nanohttpd = "2.3.1"
okhttp = "4.12.0"
protobufKotlinLite = "4.27.0"
robolectric = "4.12.2"
searchpreference = "2.5.1"
seismic = "1.0.3"
sharedPreferencesMock = "1.2.4"
slf4jTimber = "3.1"
timber = "5.0.1"
triplet = "3.10.0"
turbine = "1.1.0"
workRuntimeKtx = "2.9.0"

[libraries]
acra-limiter = { module = "ch.acra:acra-limiter", version.ref = "acra" }
acra-toast = { module = "ch.acra:acra-toast", version.ref = "acra" }
acra-dialog = { module = "ch.acra:acra-dialog", version.ref = "acra" }
acra-http = { module = "ch.acra:acra-http", version.ref = "acra" }
android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidxImageCropper" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragmentKtx" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidxExifinterface" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidxActivity" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidxPreferenceKtx" }
androidx-media = { module = "androidx.media:media", version.ref = "androidxMedia" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxUiautomator" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidxWebkit" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidxViewpager2" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidxSwiperefreshlayout" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "androidxSqliteFramework" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerview" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoServiceAnnotations" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
colorpicker = { module = "com.github.mrudultora:Colorpicker", version.ref = "colorpicker" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commonsCollections4" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
desugar-jdk-libs-nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar-jdk-libs-nio" }
drakeet-drawer = { module = "com.drakeet.drawer:drawer", version.ref = "drawer" }
mikehardy-google-analytics-java7 = { module = "net.mikehardy:google-analytics-java7", version.ref = "mikehardyGoogleAnalyticsJava7" }
ankiBackend-backend = { module = "io.github.david-allison:anki-android-backend", version.ref = "ankiBackend" }
ankiBackend-testing = { module = "io.github.david-allison:anki-android-backend-testing", version.ref = "ankiBackend" }
java-semver = { module = "com.github.zafarkhaja:java-semver", version.ref = "javaSemver" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
tapTargetPrompt = { module = "uk.co.samuelwall:material-tap-target-prompt", version.ref = "materialTapTargetPrompt" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
android-lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
android-lint = { module = "com.android.tools.lint:lint", version.ref = "lint" }
android-lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }
search-preference = { module = "com.github.ByteHamster:SearchPreference", version.ref = "searchpreference" }
seismic = { module = "com.squareup:seismic", version.ref = "seismic" }
slf4j-timber = { module = "com.arcao:slf4j-timber", version.ref = "slf4jTimber" }
jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }


#testing libs
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidxFragmentKtx" }
androidx-fragment-testing-manifest = { module = "androidx.fragment:fragment-testing-manifest", version.ref = "androidxFragmentKtx" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidTestJunit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxRunner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTextCore" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTextCore" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workRuntimeKtx" }
commons-exec = { module = "org.apache.commons:commons-exec", version.ref = "commonsExec" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
ivanshafran-shared-preferences-mock = { module = "io.github.ivanshafran:shared-preferences-mock", version.ref = "sharedPreferencesMock" }
json = { module = "org.json:json", version.ref = "json" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiterParams" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junitVintageEngine" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlinTest" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlinTest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
amazonappstorepublisher = { id = "app.brant.amazonappstorepublisher", version.ref = "amazonappstorepublisher" }


tripletPlay = { id = "com.github.triplet.play", version.ref = "triplet" }


kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }


